### ISSUE TITLE
Problems with second level directory

### ISSUE THREAD

**Issue by ghost** [rprieto/thumbsup#34]
If I make a second level directory, like my_album/first/second it won't work:

Error: ENOENT, open '/home/data1/protected/public_html/www.yourweb.com/images/show/first/second.html']
  errno: 34,
  code: 'ENOENT',
  path: '/home/data1/protected/public_html/www.yourweb.com/images/show/first/second.html' }

**Comment by kremlinkev** [comment]
From the ```README.MD```:

```
Any folder with photos and videos. thumbsup currently supports 1 level of subfolders, where they each become a gallery.
```

Being able to nest albums would be nice, but the functionality current needs to be written.

**Comment by rmaddox** [comment]
I see this, I wrongly understood, that 2 levels would be handled. Thank you.

**Comment by rprieto** [comment]
@kremlinkev is right this was by design to keep it simple. I'm actually open to having multiple levels, it wouldn't change much to the processing part of `thumbsup`. However I got stuck on design ideas to make it work / browsable.... I'll leave this thread open if people want to discuss ideas:

- what should the homepage look like?
- what does the navigation look like?
- can you see the whole navigation at once, or do you only see child folders + an "up" button?

Note that if we move to nested folders I'm even more keen on implementing #32.

**Comment by rmaddox** [comment]
It would be enough to show few pictures from folder and sub-folder, and it should be clear, that there are e.g. 3 sub-folders, like there is statistics: 5 pictures, you put it as 5 pictures, 3 sub-folders. Something like that.

**Comment by kremlinkev** [comment]
Maybe leverage breadcrumbs a la bootstrap style? When entering a nested gallery, it would show TopGal -> SubGal

Or maybe have the subgals in a row underneath?
